"""
run_clicked 블록을 Queue-aware 버전으로 교체하는 스크립트.
"""
import os

target = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'pages', '3_Document_Analysis.py')

with open(target, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find "        if run_clicked:" line (8 spaces)
start_line = None
for i, line in enumerate(lines):
    if line.rstrip() == '        if run_clicked:':
        start_line = i
        break

if start_line is None:
    print("ERROR: 'if run_clicked:' not found")
    exit(1)

# End marker: "    if not active_plan:" (4 spaces)
end_line = None
for i in range(start_line + 1, len(lines)):
    if lines[i].rstrip() == '    if not active_plan:':
        end_line = i
        break

if end_line is None:
    print("ERROR: end marker not found")
    exit(1)

print(f"Replacing lines {start_line+1}-{end_line} ({end_line - start_line} lines)")

new_block = (
    "        queue_waiting = st.session_state.get('_queue_waiting', False)\n"
    "        if run_clicked or queue_waiting:\n"
    "            _q_uid = st.session_state.get('user_id')\n"
    "            _q_pid = st.session_state.get('current_project_id')\n"
    "\n"
    "            # 최초 버튼 클릭 시만 대기열 진입 (queue_waiting 재진입 시는 스킵)\n"
    "            if run_clicked and not queue_waiting:\n"
    "                try:\n"
    "                    from database.queue_manager import enter_queue\n"
    "                    if _q_uid:\n"
    "                        enter_queue(_q_uid, _q_pid)\n"
    "                except Exception as _qe:\n"
    "                    print(f'[Queue] enter_queue 오류: {_qe}')\n"
    "\n"
    "            # 내 차례 확인\n"
    "            _can_go = True\n"
    "            try:\n"
    "                from database.queue_manager import can_process, get_queue_info, start_processing, exit_queue as _q_exit\n"
    "                if _q_uid:\n"
    "                    _can_go = can_process(_q_uid)\n"
    "            except Exception as _qe:\n"
    "                print(f'[Queue] can_process 오류: {_qe}')\n"
    "\n"
    "            if not _can_go:\n"
    "                # 대기 중 → 3초 후 자동 재확인\n"
    "                try:\n"
    "                    _q_info = get_queue_info(_q_uid) if _q_uid else {}\n"
    "                except Exception:\n"
    "                    _q_info = {}\n"
    "                _q_pos = _q_info.get('position', '?')\n"
    "                st.session_state['_queue_waiting'] = True\n"
    "                st.warning(f'⏳ 다른 사용자가 분析 중입니다. 현재 **{_q_pos}번째 대기 중**입니다. 잠시 후 자동 재확인합니다...')\n"
    "                time.sleep(3)\n"
    "                st.rerun()\n"
    "            else:\n"
    "                # 내 차례 → processing 전환 후 분析 실행\n"
    "                st.session_state['_queue_waiting'] = False\n"
    "                try:\n"
    "                    if _q_uid:\n"
    "                        start_processing(_q_uid)\n"
    "                except Exception as _qe:\n"
    "                    print(f'[Queue] start_processing 오류: {_qe}')\n"
    "\n"
    "                analyzer = get_cot_analyzer()\n"
    "                if analyzer is None:\n"
    "                    st.error('분析기를 초기화할 수 없습니다. 위의 오류 메시지를 확인하세요.')\n"
    "                    st.stop()\n"
    "                progress_placeholder = st.empty()\n"
    "                st.session_state.cot_running_block = next_block_id\n"
    "                # analysis_steps 상태 업데이트(있으면)\n"
    "                try:\n"
    "                    from database.analysis_steps_manager import set_step_status, save_step_payloads\n"
    "                    step_map = st.session_state.get('analysis_step_id_map', {}) or {}\n"
    "                    sid = step_map.get(next_block_id)\n"
    "                    if sid:\n"
    "                        set_step_status(sid, 'running')\n"
    "                        _inputs = {\n"
    "                            'feedback': st.session_state.get('cot_feedback_inputs', {}).get(next_block_id, ''),\n"
    "                            'spatial_layers': st.session_state.get('block_spatial_selection', {}).get(next_block_id, []),\n"
    "                        }\n"
    "                        save_step_payloads(sid, inputs=_inputs, outputs=None)\n"
    "                except Exception as _run_db_err:\n"
    "                    print(f'[AnalysisSteps] running 업데이트 실패: {_run_db_err}')\n"
    "\n"
    "                def step_progress(message: str) -> None:\n"
    "                    st.session_state.cot_progress_messages.append(message)\n"
    "                    if len(st.session_state.cot_progress_messages) > 50:\n"
    "                        st.session_state.cot_progress_messages = st.session_state.cot_progress_messages[-50:]\n"
    "                    progress_placeholder.info(message)\n"
    "\n"
    "                # 사용자 피드백\n"
    "                user_feedback = st.session_state.cot_feedback_inputs.get(next_block_id, '').strip()\n"
    "                combined_feedback = user_feedback or None\n"
    "\n"
    "                # 블록별 RAG 컨텍스트 주입\n"
    "                doc_rag_system = st.session_state.get('doc_rag_system')\n"
    "                if doc_rag_system and next_block:\n"
    "                    try:\n"
    "                        from rag_helper import get_block_relevant_context\n"
    "                        block_context = get_block_relevant_context(next_block, doc_rag_system, top_k=8)\n"
    "                        if block_context:\n"
    "                            # 원본 전체 텍스트는 보존하고 블록 전용 컨텍스트를 주입\n"
    "                            original_file_text = st.session_state.cot_session['project_info'].get('file_text', '')\n"
    "                            st.session_state.cot_session['project_info']['_original_file_text'] = original_file_text\n"
    "                            st.session_state.cot_session['project_info']['file_text'] = block_context\n"
    "                            print(f'[RAG] {next_block_id}: 블록 컨텍스트 주입 ({len(block_context)}자 / 전체 {len(original_file_text)}자)')\n"
    "                    except Exception as _rag_inject_err:\n"
    "                        print(f'[RAG] 컨텍스트 주입 실패 (전체 문서로 폴백): {_rag_inject_err}')\n"
    "\n"
    "                try:\n"
    "                    with st.spinner('분析 실행 중...'):\n"
    "                        step_result = analyzer.run_cot_step(\n"
    "                            next_block_id,\n"
    "                            next_block,\n"
    "                            st.session_state.cot_session,\n"
    "                            progress_callback=step_progress,\n"
    "                            step_index=st.session_state.cot_current_index + 1,\n"
    "                            feedback=combined_feedback\n"
    "                        )\n"
    "                finally:\n"
    "                    st.session_state.cot_running_block = None\n"
    "                    # 대기열에서 제거 (완료/중단/오류 모두)\n"
    "                    try:\n"
    "                        if _q_uid:\n"
    "                            _q_exit(_q_uid)\n"
    "                    except Exception as _qe:\n"
    "                        print(f'[Queue] exit_queue 오류: {_qe}')\n"
    "                    # 블록별 컨텍스트 주입 후 원본 텍스트 복원\n"
    "                    if st.session_state.cot_session and 'project_info' in st.session_state.cot_session:\n"
    "                        original = st.session_state.cot_session['project_info'].pop('_original_file_text', None)\n"
    "                        if original is not None:\n"
    "                            st.session_state.cot_session['project_info']['file_text'] = original\n"
    "\n"
    "                if step_result.get('success'):\n"
    "                    st.session_state.cot_session = step_result['cot_session']\n"
    "                    st.session_state.cot_results[next_block_id] = step_result['analysis']\n"
    "                    analysis_result = step_result['analysis']\n"
    "                    st.session_state.analysis_results[next_block_id] = analysis_result\n"
    "\n"
    "                    # Citations 저장\n"
    "                    if step_result.get('all_citations'):\n"
    "                        st.session_state.cot_citations[next_block_id] = step_result['all_citations']\n"
    "\n"
    "                    # Phase 3: 출처 검증\n"
    "                    _run_rag = st.session_state.get('doc_rag_system')\n"
    "                    if _run_rag and analysis_result:\n"
    "                        try:\n"
    "                            from rag_helper import verify_analysis\n"
    "                            _verifications = verify_analysis(analysis_result, _run_rag, max_claims=6)\n"
    "                            if _verifications:\n"
    "                                st.session_state.cot_verifications[next_block_id] = _verifications\n"
    "                        except Exception as _ver_err:\n"
    "                            print(f'[Verify] 출처 검증 실패: {_ver_err}')\n"
    "\n"
    "                    # analysis_steps 출력 저장(있으면)\n"
    "                    try:\n"
    "                        from database.analysis_steps_manager import set_step_status, save_step_payloads\n"
    "                        step_map = st.session_state.get('analysis_step_id_map', {}) or {}\n"
    "                        sid = step_map.get(next_block_id)\n"
    "                        if sid:\n"
    "                            outp = {\n"
    "                                'analysis': analysis_result,\n"
    "                                'citations': st.session_state.get('cot_citations', {}).get(next_block_id),\n"
    "                                'verifications': st.session_state.get('cot_verifications', {}).get(next_block_id),\n"
    "                            }\n"
    "                            save_step_payloads(sid, inputs=None, outputs=outp)\n"
    "                            set_step_status(sid, 'completed')\n"
    "                    except Exception as _save_step_err:\n"
    "                        print(f'[AnalysisSteps] step 저장 실패: {_save_step_err}')\n"
    "\n"
    "                    # 자동 저장\n"
    "                    project_info = {\n"
    "                        'project_name': st.session_state.get('project_name', ''),\n"
    "                        'location': st.session_state.get('location', '')\n"
    "                    }\n"
    "                    save_analysis_result(next_block_id, analysis_result, project_info)\n"
    "\n"
    "                    st.session_state.cot_history = step_result['cot_session'].get('cot_history', st.session_state.cot_history)\n"
    "                    st.session_state.cot_current_index += 1\n"
    "\n"
    "                    # 분析 진행 상태 실시간 저장\n"
    "                    try:\n"
    "                        from auth.session_init import save_analysis_progress, save_work_session\n"
    "                        save_analysis_progress(force=True)  # 즉시 저장\n"
    "                        save_work_session()\n"
    "                    except Exception as e:\n"
    "                        print(f'세션 저장 오류: {e}')\n"
    "\n"
    "                    st.success(f'{next_block_name} 블록 분析이 완료되었습니다.')\n"
    "                    st.rerun()\n"
    "                else:\n"
    "                    # 실패 상태 저장(있으면)\n"
    "                    try:\n"
    "                        from database.analysis_steps_manager import set_step_status\n"
    "                        step_map = st.session_state.get('analysis_step_id_map', {}) or {}\n"
    "                        sid = step_map.get(next_block_id)\n"
    "                        if sid:\n"
    "                            set_step_status(sid, 'failed', error=str(step_result.get('error', ''))[:800])\n"
    "                    except Exception as _fail_step_err:\n"
    "                        print(f'[AnalysisSteps] failed 업데이트 실패: {_fail_step_err}')\n"
    "                    st.error(f'{next_block_name} 블록 분析 실패: {step_result.get(\"error\", \"알 수 없는 오류\")}')\n"
    "\n"
)

result_lines = lines[:start_line] + [new_block] + lines[end_line:]

with open(target, 'w', encoding='utf-8') as f:
    f.writelines(result_lines)

print(f"Done. Total lines: {len(result_lines)}")
