[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
fileWatcherType = "none"
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[global]
developmentMode = false

[client]
showErrorDetails = false
